// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package git

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// CloneRepository provides a mock function for the type MockManager
func (_mock *MockManager) CloneRepository(ctx context.Context, url string, subPath string, reference string, auth map[string][]byte) (*Repository, error) {
	ret := _mock.Called(ctx, url, subPath, reference, auth)

	if len(ret) == 0 {
		panic("no return value specified for CloneRepository")
	}

	var r0 *Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string][]byte) (*Repository, error)); ok {
		return returnFunc(ctx, url, subPath, reference, auth)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string][]byte) *Repository); ok {
		r0 = returnFunc(ctx, url, subPath, reference, auth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, map[string][]byte) error); ok {
		r1 = returnFunc(ctx, url, subPath, reference, auth)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_CloneRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneRepository'
type MockManager_CloneRepository_Call struct {
	*mock.Call
}

// CloneRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - subPath string
//   - reference string
//   - auth map[string][]byte
func (_e *MockManager_Expecter) CloneRepository(ctx interface{}, url interface{}, subPath interface{}, reference interface{}, auth interface{}) *MockManager_CloneRepository_Call {
	return &MockManager_CloneRepository_Call{Call: _e.mock.On("CloneRepository", ctx, url, subPath, reference, auth)}
}

func (_c *MockManager_CloneRepository_Call) Run(run func(ctx context.Context, url string, subPath string, reference string, auth map[string][]byte)) *MockManager_CloneRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string][]byte
		if args[4] != nil {
			arg4 = args[4].(map[string][]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockManager_CloneRepository_Call) Return(repository *Repository, err error) *MockManager_CloneRepository_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *MockManager_CloneRepository_Call) RunAndReturn(run func(ctx context.Context, url string, subPath string, reference string, auth map[string][]byte) (*Repository, error)) *MockManager_CloneRepository_Call {
	_c.Call.Return(run)
	return _c
}
