apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: faas-console-plugin
  labels:
    app: faas-console-plugin
    app.kubernetes.io/name: faas-console-plugin
    app.kubernetes.io/part-of: faas-console-plugin
    app.kubernetes.io/managed-by: kustomize
spec:
  displayName: OpenShift Serverless Functions Console Plugin
  i18n:
    loadType: Preload
  backend:
    type: Service
    service:
      name: faas-console-plugin
      namespace: func-operator-system
      port: 9443
      basePath: /
  proxy:
  - alias: backend
    endpoint:
      type: Service
      service:
        name: faas-console-plugin
        namespace: func-operator-system
        port: 9443
