apiVersion: v1
kind: Service
metadata:
  name: faas-console-plugin
  namespace: system
  labels:
    app: faas-console-plugin
    app.kubernetes.io/name: faas-console-plugin
    app.kubernetes.io/part-of: faas-console-plugin
    app.kubernetes.io/managed-by: kustomize
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: faas-console-plugin-cert
spec:
  ports:
  - name: 9443-tcp
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app: faas-console-plugin
    app.kubernetes.io/name: faas-console-plugin
  type: ClusterIP
  sessionAffinity: None
