apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-console-plugin
  namespace: system
  labels:
    app: faas-console-plugin
    app.kubernetes.io/name: faas-console-plugin
    app.kubernetes.io/part-of: faas-console-plugin
    app.kubernetes.io/managed-by: kustomize
