apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: func-operator
  name: func-operator-function-viewer-role
rules:
- apiGroups:
  - functions.dev
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - functions.dev
  resources:
  - functions/status
  verbs:
  - get
