apiVersion: v1
data:
  autoUpdateMiddleware: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: func-operator
    control-plane: controller-manager
  name: func-operator-controller-config
