apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: objectbucket-notifications-adapter
  name: objectbucket-notifications-adapter-notifications
spec:
  ports:
  - name: notifications
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/name: objectbucket-notifications-adapter
    control-plane: manager
status:
  loadBalancer: {}
