apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: CONSOLE_PLUGIN_IMAGE
          value: "faas-console-plugin:latest"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
