FROM registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.22@sha256:90309e9e551dc5e91ff7d2b6a3243bc7f258530f325a6990925560ba651827b7

ENTRYPOINT ["/bin/opm"]
CMD ["serve", "/configs", "--cache-dir=/tmp/cache"]

COPY v4.22/catalog/ /configs

RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]

LABEL operators.operatorframework.io.index.configs.v1=/configs
