apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: objectbucket-notifications-adapter
    app.kubernetes.io/managed-by: kustomize
  name: objectbucketsource-admin-role
rules:
- apiGroups:
  - sources.functions.dev
  resources:
  - objectbucketsources
  verbs:
  - '*'
- apiGroups:
  - sources.functions.dev
  resources:
  - objectbucketsources/status
  verbs:
  - get
