//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Function) DeepCopyInto(out *Function) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Function.
func (in *Function) DeepCopy() *Function {
	if in == nil {
		return nil
	}
	out := new(Function)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Function) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionList) DeepCopyInto(out *FunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Function, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionList.
func (in *FunctionList) DeepCopy() *FunctionList {
	if in == nil {
		return nil
	}
	out := new(FunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionServiceStatus) DeepCopyInto(out *FunctionServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionServiceStatus.
func (in *FunctionServiceStatus) DeepCopy() *FunctionServiceStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpec) DeepCopyInto(out *FunctionSpec) {
	*out = *in
	in.Repository.DeepCopyInto(&out.Repository)
	in.Registry.DeepCopyInto(&out.Registry)
	if in.AutoUpdateMiddleware != nil {
		in, out := &in.AutoUpdateMiddleware, &out.AutoUpdateMiddleware
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpec.
func (in *FunctionSpec) DeepCopy() *FunctionSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpecRegistry) DeepCopyInto(out *FunctionSpecRegistry) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpecRegistry.
func (in *FunctionSpecRegistry) DeepCopy() *FunctionSpecRegistry {
	if in == nil {
		return nil
	}
	out := new(FunctionSpecRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpecRepository) DeepCopyInto(out *FunctionSpecRepository) {
	*out = *in
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpecRepository.
func (in *FunctionSpecRepository) DeepCopy() *FunctionSpecRepository {
	if in == nil {
		return nil
	}
	out := new(FunctionSpecRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatus) DeepCopyInto(out *FunctionStatus) {
	*out = *in
	in.Git.DeepCopyInto(&out.Git)
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.Middleware.DeepCopyInto(&out.Middleware)
	out.Service = in.Service
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]FunctionStatusHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatus.
func (in *FunctionStatus) DeepCopy() *FunctionStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatusDeployment) DeepCopyInto(out *FunctionStatusDeployment) {
	*out = *in
	in.ImageBuilt.DeepCopyInto(&out.ImageBuilt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatusDeployment.
func (in *FunctionStatusDeployment) DeepCopy() *FunctionStatusDeployment {
	if in == nil {
		return nil
	}
	out := new(FunctionStatusDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatusGit) DeepCopyInto(out *FunctionStatusGit) {
	*out = *in
	in.LastChecked.DeepCopyInto(&out.LastChecked)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatusGit.
func (in *FunctionStatusGit) DeepCopy() *FunctionStatusGit {
	if in == nil {
		return nil
	}
	out := new(FunctionStatusGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatusHistoryEntry) DeepCopyInto(out *FunctionStatusHistoryEntry) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatusHistoryEntry.
func (in *FunctionStatusHistoryEntry) DeepCopy() *FunctionStatusHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(FunctionStatusHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatusMiddleware) DeepCopyInto(out *FunctionStatusMiddleware) {
	*out = *in
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = new(string)
		**out = **in
	}
	out.AutoUpdate = in.AutoUpdate
	in.LastRebuild.DeepCopyInto(&out.LastRebuild)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatusMiddleware.
func (in *FunctionStatusMiddleware) DeepCopy() *FunctionStatusMiddleware {
	if in == nil {
		return nil
	}
	out := new(FunctionStatusMiddleware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatusMiddlewareAutoUpdate) DeepCopyInto(out *FunctionStatusMiddlewareAutoUpdate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatusMiddlewareAutoUpdate.
func (in *FunctionStatusMiddlewareAutoUpdate) DeepCopy() *FunctionStatusMiddlewareAutoUpdate {
	if in == nil {
		return nil
	}
	out := new(FunctionStatusMiddlewareAutoUpdate)
	in.DeepCopyInto(out)
	return out
}
