apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: func-operator-consoleplugin-manager
  labels:
    app.kubernetes.io/name: func-operator
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
