apiVersion: v1
kind: Service
metadata:
  name: notifications
  labels:
    app.kubernetes.io/name: objectbucket-notifications-adapter
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: manager
    app.kubernetes.io/name: objectbucket-notifications-adapter
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: notifications
