// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package funccli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"knative.dev/func/pkg/functions"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Deploy provides a mock function for the type MockManager
func (_mock *MockManager) Deploy(ctx context.Context, repoPath string, namespace string, opts DeployOptions) error {
	ret := _mock.Called(ctx, repoPath, namespace, opts)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, DeployOptions) error); ok {
		r0 = returnFunc(ctx, repoPath, namespace, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockManager_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - namespace string
//   - opts DeployOptions
func (_e *MockManager_Expecter) Deploy(ctx interface{}, repoPath interface{}, namespace interface{}, opts interface{}) *MockManager_Deploy_Call {
	return &MockManager_Deploy_Call{Call: _e.mock.On("Deploy", ctx, repoPath, namespace, opts)}
}

func (_c *MockManager_Deploy_Call) Run(run func(ctx context.Context, repoPath string, namespace string, opts DeployOptions)) *MockManager_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 DeployOptions
		if args[3] != nil {
			arg3 = args[3].(DeployOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManager_Deploy_Call) Return(err error) *MockManager_Deploy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Deploy_Call) RunAndReturn(run func(ctx context.Context, repoPath string, namespace string, opts DeployOptions) error) *MockManager_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Describe provides a mock function for the type MockManager
func (_mock *MockManager) Describe(ctx context.Context, name string, namespace string) (functions.Instance, error) {
	ret := _mock.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Describe")
	}

	var r0 functions.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (functions.Instance, error)); ok {
		return returnFunc(ctx, name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) functions.Instance); ok {
		r0 = returnFunc(ctx, name, namespace)
	} else {
		r0 = ret.Get(0).(functions.Instance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_Describe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Describe'
type MockManager_Describe_Call struct {
	*mock.Call
}

// Describe is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockManager_Expecter) Describe(ctx interface{}, name interface{}, namespace interface{}) *MockManager_Describe_Call {
	return &MockManager_Describe_Call{Call: _e.mock.On("Describe", ctx, name, namespace)}
}

func (_c *MockManager_Describe_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockManager_Describe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_Describe_Call) Return(instance functions.Instance, err error) *MockManager_Describe_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockManager_Describe_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string) (functions.Instance, error)) *MockManager_Describe_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentVersion provides a mock function for the type MockManager
func (_mock *MockManager) GetCurrentVersion(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentVersion'
type MockManager_GetCurrentVersion_Call struct {
	*mock.Call
}

// GetCurrentVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) GetCurrentVersion(ctx interface{}) *MockManager_GetCurrentVersion_Call {
	return &MockManager_GetCurrentVersion_Call{Call: _e.mock.On("GetCurrentVersion", ctx)}
}

func (_c *MockManager_GetCurrentVersion_Call) Run(run func(ctx context.Context)) *MockManager_GetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GetCurrentVersion_Call) Return(s string, err error) *MockManager_GetCurrentVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GetCurrentVersion_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockManager_GetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestMiddlewareVersion provides a mock function for the type MockManager
func (_mock *MockManager) GetLatestMiddlewareVersion(ctx context.Context, runtime string, invoke string) (string, error) {
	ret := _mock.Called(ctx, runtime, invoke)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestMiddlewareVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, runtime, invoke)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, runtime, invoke)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, runtime, invoke)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GetLatestMiddlewareVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestMiddlewareVersion'
type MockManager_GetLatestMiddlewareVersion_Call struct {
	*mock.Call
}

// GetLatestMiddlewareVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - runtime string
//   - invoke string
func (_e *MockManager_Expecter) GetLatestMiddlewareVersion(ctx interface{}, runtime interface{}, invoke interface{}) *MockManager_GetLatestMiddlewareVersion_Call {
	return &MockManager_GetLatestMiddlewareVersion_Call{Call: _e.mock.On("GetLatestMiddlewareVersion", ctx, runtime, invoke)}
}

func (_c *MockManager_GetLatestMiddlewareVersion_Call) Run(run func(ctx context.Context, runtime string, invoke string)) *MockManager_GetLatestMiddlewareVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_GetLatestMiddlewareVersion_Call) Return(s string, err error) *MockManager_GetLatestMiddlewareVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GetLatestMiddlewareVersion_Call) RunAndReturn(run func(ctx context.Context, runtime string, invoke string) (string, error)) *MockManager_GetLatestMiddlewareVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetMiddlewareVersion provides a mock function for the type MockManager
func (_mock *MockManager) GetMiddlewareVersion(ctx context.Context, name string, namespace string) (string, error) {
	ret := _mock.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetMiddlewareVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, name, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, name, namespace)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GetMiddlewareVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMiddlewareVersion'
type MockManager_GetMiddlewareVersion_Call struct {
	*mock.Call
}

// GetMiddlewareVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockManager_Expecter) GetMiddlewareVersion(ctx interface{}, name interface{}, namespace interface{}) *MockManager_GetMiddlewareVersion_Call {
	return &MockManager_GetMiddlewareVersion_Call{Call: _e.mock.On("GetMiddlewareVersion", ctx, name, namespace)}
}

func (_c *MockManager_GetMiddlewareVersion_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockManager_GetMiddlewareVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_GetMiddlewareVersion_Call) Return(s string, err error) *MockManager_GetMiddlewareVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_GetMiddlewareVersion_Call) RunAndReturn(run func(ctx context.Context, name string, namespace string) (string, error)) *MockManager_GetMiddlewareVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockManager
func (_mock *MockManager) Run(ctx context.Context, dir string, args ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dir, args)
	} else {
		tmpRet = _mock.Called(ctx, dir)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return returnFunc(ctx, dir, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = returnFunc(ctx, dir, args...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockManager_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - dir string
//   - args ...string
func (_e *MockManager_Expecter) Run(ctx interface{}, dir interface{}, args ...interface{}) *MockManager_Run_Call {
	return &MockManager_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, dir}, args...)...)}
}

func (_c *MockManager_Run_Call) Run(run func(ctx context.Context, dir string, args ...string)) *MockManager_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManager_Run_Call) Return(s string, err error) *MockManager_Run_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockManager_Run_Call) RunAndReturn(run func(ctx context.Context, dir string, args ...string) (string, error)) *MockManager_Run_Call {
	_c.Call.Return(run)
	return _c
}
